# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LWViewControllerTransition' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LWViewControllerTransition
    pod 'Masonry' , '= 1.1.0'
  target 'LWViewControllerTransitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LWViewControllerTransitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
